// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/whoami.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
var whoami_default = defineTool({
  name: "whoami",
  title: "Who am I",
  description: "Return the signed-in user's id, email, and app roles.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { createClient } = await import("npm:@supabase/supabase-js@^2.96.0");
    const sb = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data: roles } = await sb.from("user_roles").select("role").eq("user_id", ctx.getUserId());
    const payload = {
      user_id: ctx.getUserId(),
      email: ctx.getUserEmail(),
      roles: (roles ?? []).map((r) => r.role)
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-my-registrations.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
var list_my_registrations_default = defineTool2({
  name: "list_my_registrations",
  title: "List my registrations",
  description: "List NextGen Summit registrations belonging to the signed-in user.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { createClient } = await import("npm:@supabase/supabase-js@^2.96.0");
    const sb = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data, error } = await sb.from("registrations").select("*").order("created_at", { ascending: false });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { registrations: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-scholarship-applicants.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";
var list_scholarship_applicants_default = defineTool3({
  name: "list_scholarship_applicants",
  title: "List scholarship applicants",
  description: "List scholarship applicants (admin or selection_team only, enforced by RLS). Optional status filter.",
  inputSchema: {
    status: z.enum(["pending", "shortlisted", "accepted", "rejected", "waitlist"]).optional().describe("Filter by review status."),
    limit: z.number().int().positive().max(500).optional().describe("Max rows (default 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { createClient } = await import("npm:@supabase/supabase-js@^2.96.0");
    const sb = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    });
    let q = sb.from("scholarship_applicants").select("*").order("created_at", { ascending: false }).limit(limit ?? 100);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { applicants: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/update-applicant-status.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
var update_applicant_status_default = defineTool4({
  name: "update_applicant_status",
  title: "Update applicant status",
  description: "Update a scholarship applicant's review status and optional notes. Requires admin or selection_team role (enforced by RLS).",
  inputSchema: {
    applicant_id: z2.string().uuid().describe("Applicant row id."),
    status: z2.enum(["pending", "shortlisted", "accepted", "rejected", "waitlist"]),
    notes: z2.string().optional().describe("Reviewer notes (max 1000 chars).")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ applicant_id, status, notes }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    if (notes && notes.length > 1e3) {
      return { content: [{ type: "text", text: "Notes exceed 1000-character limit" }], isError: true };
    }
    const { createClient } = await import("npm:@supabase/supabase-js@^2.96.0");
    const sb = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const patch = {
      status,
      reviewed_by: ctx.getUserId(),
      reviewed_at: (/* @__PURE__ */ new Date()).toISOString()
    };
    if (notes !== void 0) patch.notes = notes;
    const { data, error } = await sb.from("scholarship_applicants").update(patch).eq("id", applicant_id).select().maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { applicant: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ypcoludurdfinazcxylj";
var mcp_default = defineMcp({
  name: "nextgen-summit-mcp",
  title: "NextGen Summit MCP",
  version: "0.1.0",
  instructions: "Tools for NextGen Summit 2026. Use `whoami` to inspect your session, `list_my_registrations` for your own registrations, and (admin/selection_team only) `list_scholarship_applicants` / `update_applicant_status` for scholarship review.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    whoami_default,
    list_my_registrations_default,
    list_scholarship_applicants_default,
    update_applicant_status_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
